### ISSUE TITLE
#define preproc statement values in C using TSerror highlight?

### ISSUE THREAD

**Issue by OddBread** [rktjmp/lush.nvim#104]
I'm not entirely sure why, but when using my lush theme, trying to use a define preproc causes the value i try to assign it to show up using whatever i set as 'TSerror' in config, as i am using treesitter alongside it. I have tried to use other theme, no matter if it was made with lush or not, the error goes away. I have no clue what i might have done to cause this, since nothing is defined to use the error color besides error themselves. I can send my lush config over if need be. [here is what it looks like when using my theme.](https://files.catbox.moe/onlxod.png)

**Comment by OddBread** [comment]
Also, [the issue being fixed upon switching to another lush scheme](https://files.catbox.moe/o58skt.png)

**Comment by rktjmp** [comment]
Do you have treesitter enabled? Try `:TSDisable highlight`.

Most likely the other scheme defines some specific C TS colorings while yours is falling back through some defaults which might link to TSError/Error.

Try poking at `hi TSPreProc`, `hi PreProc` etc and see what they say.

**Comment by OddBread** [comment]
`hi TSPreProc` links to PreProc, `hi PreProc` says `guifg=#7f8c54`, which seems normal. Disabling TS makes the error highlighting go away.

**Comment by rktjmp** [comment]
Not sure. You might have to post the code. I don't really think it's an internal lush thing as we just pass groups down and there is nothing special about TSPreProc, etc but perhaps there is a group linking issue or something.

**Comment by OddBread** [comment]
[here is my theme](https://files.catbox.moe/5rin9m.7z). Not too big of an issue if you can't figure out what's wrong with it, but i might as well send it just in case

**Comment by rktjmp** [comment]
The lack of `;` at the end of the line makes Treesitter mark the last symbol as `cTSError` -> `TSError`.

  
![image](https://user-images.githubusercontent.com/866010/186734717-5214a4c5-1c6a-4e4d-bbb0-78e7acb710fb.png)
