### ISSUE TITLE
Using new Treesitter groups/tags

### ISSUE THREAD

**Issue by OkanEsen** [rktjmp/lush.nvim#107]
Hi!

Is there a way to comply with the new way of how the Treesitter highlight groups are used in Neovim +0.8? Previously the old group names were prefixed with a `TS*` prefix but this is deprecated now (https://github.com/nvim-treesitter/nvim-treesitter/pull/3656) and one has to use the tags now (`TSError` -> `@error`).

I tried to use these tags as names for my theme but that unfortunately doesn't work. I don't think, this is possible with how the spec is currently defined right?

Example:
```lua
-- Old
TSError {Red},

-- New
@error {Red},
-- I intuitively tried these as well but they don't work either.
-- "@error" {Red},
-- ["@error"] {Red},
```

**Comment by rktjmp** [comment]
First I've seen of this!

Hm... Will have to think about if it's possible. `TSError` is basically injected into a scope under that name, but `@error` isn't a valid lua name so ... Seems we have to support `@x.y` variants too.

There are a few options or at least work arounds, but they wont work with Lushify:

1. manually define some `hi link @error my_at_error_group` in your theme/config
2. Use the build system (`BUILD.md`) and manually apply some post-processing to the highlight groups returned, so you could convert the group named `ATError` to `@error`.
3. ... ?

**Comment by OkanEsen** [comment]
Yeah, no worries and thank you for your reply. It's a little unfortunate, that the prefixes were dropped but that's how it is. :-)

I think I'll go with your first suggestion for now, thank you very much!

**Comment by clason** [comment]
`@` and `.` are officially supported in highlight group identifiers in Nvim 0.8 (before, they triggered a warning -- not an error -- but still worked).

This was noted in Neovim's pinned "Following HEAD" issue when the change was made back in August. (Plugin authors are strongly encouraged to subscribe to this issue, especially when they rely on experimental features like treesitter support.)

**Comment by rktjmp** [comment]
See https://github.com/rktjmp/lush.nvim/issues/109
