### ISSUE TITLE
How to specify treesitter highlight groups?

### ISSUE THREAD

**Issue by antistic** [rktjmp/lush.nvim#108]
`:h treesitter-highlight-groups` describes highlight groups such as `@comment` `@comment.lua`.

Lua doesn't allow symbols like `@` and `.` in names, so you can't do:

```lua
local lush = require('lush')
return lush(function()
	return {
		@comment { },
		@comment.lua { },
	}
end)
```

For `@comment` the workaround is using the default link `TSComment` or `Comment` instead, but I can't work out if there's a similar workaround for language specific groups.

**Comment by rktjmp** [comment]
#107

**Comment by rktjmp** [comment]
See https://github.com/rktjmp/lush.nvim/issues/109 for fix.
