### ISSUE TITLE
Theme the nvim-cmp

### ISSUE THREAD

**Issue by ccl1115** [rktjmp/lush.nvim#112]
I added some highlight definitions for nvim-cmp. But it won't apply unless I manually use `:Lushify` to the theme file.

<img width="840" alt="Screen Shot 2022-10-27 at 12 21 50" src="https://user-images.githubusercontent.com/165493/198190944-f1c0e36d-4869-4b50-b5d0-366482051f84.png">

**Comment by rktjmp** [comment]
You'll have to ask nvim-cmp's creators.

**Comment by ccl1115** [comment]
Thanks.
