### ISSUE TITLE
`Cursor` highlight group appears not to be working

### ISSUE THREAD

**Issue by lyh970817** [rktjmp/lush.nvim#120]
Using `LushRunTutorial` as a minimum example, `Cursor` doesn't seem to take effect. 
![2023-03-04-1677922380](https://user-images.githubusercontent.com/32429705/222891075-c2fe2227-cedc-4b82-b9d6-ab79be8cf441.jpg)

**Comment by rktjmp** [comment]
Cursor color can be effected by your terminal or other runtime and might need extra settings, or be unsupported.
