### ISSUE TITLE
Error `bad argument #1 to 'unpack' (table expected, got nil)`

### ISSUE THREAD

**Issue by rockyzhang24** [rktjmp/lush.nvim#136]
I built the nvim with latest commit, NVIM v0.10.0-dev-1164+g23c21e763. Then I opened nvim and got this error

<img width="1728" alt="image" src="https://github.com/rktjmp/lush.nvim/assets/11582667/ce1f713e-5cdf-4fea-ac61-782cb1821203">

Thank you.

**Comment by rockyzhang24** [comment]
Update: it caused by this commit https://github.com/neovim/neovim/commit/e99a3fd25daeb52f609c72cb7e96b83bd0610e9e

**Comment by rktjmp** [comment]
I'm unable to reproduce this with arctic main or v2, against 23c21e763 (reported) or f094db0e5 (latest).

**Comment by rockyzhang24** [comment]
That's weird. I found the error happens since this commit https://github.com/neovim/neovim/commit/e99a3fd25daeb52f609c72cb7e96b83bd0610e9e where the Luajit is updated. Not sure whether it is caused by Luajit.

**Comment by rktjmp** [comment]
Does it occur when you use the latest version of your theme from online?

To me the error reads that this line isn't a table (malformed some how?)

https://github.com/rockyzhang24/arctic.nvim/blob/26a87e8d3832dc4db8cae9d581552f7b51eed6b6/lua/lush_theme/arctic.lua#L236

Or possibly its parent group

https://github.com/rockyzhang24/arctic.nvim/blob/26a87e8d3832dc4db8cae9d581552f7b51eed6b6/lua/lush_theme/arctic.lua#L231

**Comment by rockyzhang24** [comment]
Thank you for your investigating. I tried to comment out these lines but the error is still there.

**Comment by rktjmp** [comment]
Not sure. Without a preproduction I cant really do much more.

**Comment by rockyzhang24** [comment]
Yes I know. Thank you so much for your help.

**Comment by rktjmp** [comment]
Please re-open if you or anyone can ever reproduce :)
