### ISSUE TITLE
altfont style support is missing

### ISSUE THREAD

**Issue by t184256** [rktjmp/lush.nvim#142]
specifying `{gui="altfont"}` is simply ignored

code pointers:

https://github.com/rktjmp/lush.nvim/blob/2e8d34e748642621d761a65e3c2a198154b914e8/lua/lush/compiler.lua#L64
https://github.com/rktjmp/lush.nvim/blob/2e8d34e748642621d761a65e3c2a198154b914e8/doc/lush.txt#L310

**Comment by rktjmp** [comment]
[5337450](https://github.com/rktjmp/lush.nvim/commit/533745028d613ae59e969329d21e7b210c37fdb2)

Thanks.
