### ISSUE TITLE
"Cannot find color scheme ..."

### ISSUE THREAD

**Issue by jbrilha** [rktjmp/lush.nvim#149]
Hello,

I feel really dumb but I'm having trouble getting Lazy to detect my color scheme,

I'm following CREATE.md and my color scheme is in ~/colorscheme/custom as shown below but it always throws the error that it can't be found.
I've replaced "lush_template" with "custom" in custom.lua as shown as well

Am I missing something?

Thank you!

<img width="1508" alt="Screenshot 2024-07-23 at 04 07 25" src="https://github.com/user-attachments/assets/935477b8-1916-454e-8f44-88dc3656cb51">

**Comment by rktjmp** [comment]
Not sure, this works for me fine. Did you run `:Lazy`? It might have to create some links and stuff etc.

![image](https://github.com/user-attachments/assets/0d67b875-2586-4687-88ac-8fd14b06cb62)

**Comment by jbrilha** [comment]
two things were wrong, first being that on Mac I should have pointed to Users/.... instead of home/....

second and more tragic is that I could either load my other plugins and it wouldn't work OR comment out the setup("plugins") line and just load Lush by itself using the approach in your screenshot

I got it to work by creating a lush.lua file inside my plugins directory with the following contents so that Lazy can actually pick it up as a plugin along with my other stuff
<img width="751" alt="Screenshot 2024-07-23 at 13 17 08" src="https://github.com/user-attachments/assets/50a7a5be-7b6d-479d-9157-f30371579aa3">

is it okay if I make a PR adding this info (succinctly) to CREATE.md? I feel like this is a common way to organize plugins and it could maybe save someone the confusion in the future.

either way sorry for the hassle and thank you for the support!

**Comment by rktjmp** [comment]
In hindsight it makes sense that Lazy probably only supports one call to setup, I dont have a lot of experience with it.

Drop a PR, probably you could explain it all with a comment in the lazy example saying to put the { dir = ... } ("plugin spec"?) inside its own file when using the "plugins dir" style or whatever lazy calls it? See how you go.
