### ISSUE TITLE
Consider mentioning fwatch.nvim in the README file

### ISSUE THREAD

**Issue by oclay1st** [rktjmp/lush.nvim#156]
@rktjmp Please, consider mentioning fwatch.nvim on the README file in order to improve the realtime experience while creating a colorscheme. Thanks

**Comment by rktjmp** [comment]
How do you use `fwatch.nvim`, in a way that `:Lushify` doesn't cover you?

**Comment by oclay1st** [comment]
I don't know if I'm doing something wrong but as far as I know `:Lushify` only works for the lua code on the colorscheme, right?.  
So, normally I start two nvim sessions, one to work on the colorscheme (it will be similar to Intellij Idea for Java) and the other to see the results with the highlighted Java code. 
I use `fwatch.nvim` to get realtime updates and speed the development without applying the colorscheme all the time on the second session.

**Comment by rktjmp** [comment]
Sorry for not replying, I feel a bit weird promoting fwatch.nvim specifically in the readme but have been curious about cross-process syncing but probably simpler to just open other syntax files in a split.
