### ISSUE TITLE
Investigate LSP highlighting weirdery

### ISSUE THREAD

**Issue by rktjmp** [rktjmp/lush.nvim#21]
When setting LSP highlight groups, they sometimes

- aren't applied immediately
  - pretty sure this is because vir text highlights arent cleared like normal groups, so they retain old settings
- cant use group linking
  - I think? Same issu as above maybe.
- mess with the dynamic highlighting of other groups
  - maybe if the group has some LSP content on it?

**Comment by rktjmp** [comment]
Or maybe it works just fine...?

**Comment by kunzaatko** [comment]
I changed them recently and it was normal. Changed instantly...
