### ISSUE TITLE
Error format hsl

### ISSUE THREAD

**Issue by devlcp** [rktjmp/lush.nvim#26]
Error:
`Lush.ify: Could not parse buffer due to Lua error: line 32: unexpected symbol near ','`

Line: 
`CursorLine  { bg = hsl(228, 19%, 20%) }`

Note: Doesn't accept hsl colors only hexadecimal.

**Comment by rktjmp** [comment]
Should be `CursorLine { bg = hsl(228, 19, 20) }`.
