### ISSUE TITLE
Request: Highlighting calls of the form `hsl '#rrggbb'` like normal `hsl('#rrggbb')`

### ISSUE THREAD

**Issue by Joakker** [rktjmp/lush.nvim#40]
Currently, a construction of the form `hsl('#rrggbb')` is highlighted with the proper colour background under `:Lushify`. However, if I were to do the equivalent `hsl '#rrggbb'`, while it yields the same value, it isn't highlighted in any special way at all.

This isn't a huge problem, but if the user's coding style prefers the later construction over the former in cases like this, they'd loose on the real-time feedback the plugin brings.

**With brackets**

![image](https://user-images.githubusercontent.com/51842726/116955454-91ed0680-ac60-11eb-894e-22c5ca8842ad.png)

**Without brackets**

![image](https://user-images.githubusercontent.com/51842726/116955500-c06ae180-ac60-11eb-804e-c0682867568e.png)

**Comment by rktjmp** [comment]
Fixed in bcc4046db0adce9dbc95064207caf40e3cc6212d
