### ISSUE TITLE
.darken/.lighten and other functions of this kind aren't working

### ISSUE THREAD

**Issue by iRealistiX** [rktjmp/lush.nvim#66]
Basically, I am creating my `onedark-pro` theme (available on vs-code extentions market) variant for neovim, `lush.nvim` parser is amazing, but for some reason the functions to darken and lighten the colors does not work.

Yes I declared the `Normal` before the comment section, as shown here.

Any help would be appreciated, thanks!

![21-09-05_20h:41](https://user-images.githubusercontent.com/67875888/132137884-224b3248-0b3e-45a7-a6d0-586661017819.png)

**Comment by rktjmp** [comment]
You have to wrap the strings in a call to `hsl`/`hsluv` so they are the correct internal types, which have the operations attached.

`Normal { bg = hsluv("#2c323c") }`

The reason values aren't automatically wrapped (as might be expected) is to keep Lush  somewhat agnostic to what you give it (i.e. you could drop in a CMYK library or whatever as long as `tostring(v) -> #hexhex`).

**Comment by iRealistiX** [comment]
Thanks, the `hsluv` function is basically what I need (since I don't want to deal with hsl because all the colors are already in hex)
