### ISSUE TITLE
setting underline color

### ISSUE THREAD

**Issue by jacksonludwig** [rktjmp/lush.nvim#67]
Thanks for the plugin.

I am looking to highlight LSP colors with an underline that is a different color from the text itself (e.g. the text can be any color while the underline should always be red).

Would you be able to point me in the direction to do this? Usually I think `guisp` controls underline color but I can't see the effect while using lush and doing something like 
```
DiagnosticUnderlineError { bg = palette.background, gui = "underline", guisp = "palette.red" }
```
The underline shows but remains the color of the foreground.

**Comment by rktjmp** [comment]
The key should be `sp`, inline with `bg`, `fg` where we strip `gui` from the key name. Support may be dependent on your terminal, not sure.

```
Direct Definition                                  *lush-spec-direct-definition*

Used to define a stand alone highlight group.

Syntax:
>
  GroupName { fg = value, bg = value, gui = value, sp = value, blend = value }
<

Supports the following keys:

  fg:    sets the `guifg` property of a Vim highlight group.

  bg:    sets the `guibg` property of a Vim highlight group.

  gui:   sets the `gui` property of a Vim highlight group.

  sp:    sets the `guisp` property of a Vim highlight group.

  blend: sets the `blend` property of a Vim highlight group.

```

**Comment by jacksonludwig** [comment]
Thanks for the info. My mistake on the syntax. I'll have to confirm but I think there was an issue with windows terminal displaying the different colored underline as well.

**Comment by rktjmp** [comment]
Yeah, it doesn't work in `alacritty` but does in `kitty` for example. I imagine it's more likely to be unsupported than supported in most terminals.

From memory Windows Terminal had issues with bold (or was it italic?) font faces etc until recently so I think their font decoration handling might be pretty spotty.
