### ISSUE TITLE
Hex colors slightly off?

### ISSUE THREAD

**Issue by mcchrish** [rktjmp/lush.nvim#68]
```lua
local lush = require "lush"

local c = lush.hsl("#fbf1c7")
print(c.h, c.s, c.l, c.hex) -- 48 87 88 #FBF0C6
```

Should still be `#fbf1c7` instead of `#FBF0C6`.

**Comment by rktjmp** [comment]
See https://github.com/rktjmp/lush.nvim/issues/59, *to me* it is not an issue in practical use. If you can find lossless conversion code, that is actually lossless, I am open to it.

**Comment by mcchrish** [comment]
I didn't see there's a length discussion about it already. Indeed, in practical use it doesn't really matter that much. I only notice since I'm comparing them side-by-side and looking at them intensely.

**Comment by rktjmp** [comment]
Yeah I wish there was an easy fix, maybe one day I will have time to look into it again. As I said in that other thread, I would bet in real terms, the differences between monitors and terminal rendering pipelines probably has a way more noticeable impact than the fractional differences in color codes. Probably healthiest to not sweat over it too hard.

**Comment by mcchrish** [comment]
I just remembered, is it possible to store the original hex somewhere (maybe just a key `{ orig_hex = "#fffff" }` in hsl table)  and then use it when compiling? That might be a possible work around.
