### ISSUE TITLE
Overcoming hsl's lossy conversions to hex

### ISSUE THREAD

**Issue by ryansch** [rktjmp/lush.nvim#74]
I've been working in a solarized dark variant here: https://github.com/ryansch/lunarized

After experimenting with the `hsl` function, it became clear to me that the conversion from hsl to the final hex that neovim uses is not exact.

Example: I specify "#002b36" as the base03 color (https://github.com/ryansch/lunarized/blob/843fc965500266649fe2778a889a8ac5b57158a6/lua/lush_theme/lunarized.lua#L58). If I wrap that color with `hsl`, neovim actually ends up with "#002d38".

Is this just a limitation of how `hsl` models the colorspace? I'd really like to be able to use the various functions in lush to generate color variants but I'd also like my colors to be accurate.

**Comment by ryansch** [comment]
@rktjmp I was able to apply your strategy to rework my color palette!

https://github.com/ryansch/lunarized/blob/7b18694952c4a78e7c3765e03b5c588775e1c83a/lua/lush_theme/lunarized.lua#L57

Thanks!

**Comment by rktjmp** [comment]
Great! Check out the new [BUILD.md](https://github.com/rktjmp/lush.nvim/blob/main/BUILD.md) for a guide on converting your theme for use in other programs if you want.
