### ISSUE TITLE
Compile option to mirror gui to cterm

### ISSUE THREAD

**Issue by mcchrish** [rktjmp/lush.nvim#75]
Turns out `termguicolors` are not the same in Vim and Neovim. https://github.com/vim/vim/issues/1740
Neovim uses gui while Vim uses cterm.

Solution: add an option to just copy the gui value to cterm on compile. Something like `copy_cterm_from_gui = true`. Default to `false`.

**Comment by mcchrish** [comment]
PR: https://github.com/rktjmp/lush.nvim/pull/76

**Comment by rktjmp** [comment]
https://github.com/rktjmp/lush.nvim/blob/main/lua/shipwright/transform/lush/vim_compatible_vimscript.lua
