### ISSUE TITLE
How do I use Lush?

### ISSUE THREAD

**Issue by Risto-Stevcev** [rktjmp/lush.nvim#80]
1. Ran the quickstart `:LushRunQuickstart`
2. Ran `Lushify`
3. Uncommented 'Normal'

The tutorial says:
-- You should be on the water now, Lush.ify has automatically recognized
-- our Highlight definition and applied it in real time.

But nothing happens
Am I missing a step? If not then what can I do to debug further?

**Comment by rktjmp** [comment]
That should be all you need to do. You should see neovims background turn blue.

What version of nvim are you using? OS _shouldn't_ matter. What does `:messages` print out?

**Comment by Risto-Stevcev** [comment]
Here are some screenshots in case it's useful:
1. Started neovim:
![image](https://user-images.githubusercontent.com/6767374/142782532-954287ab-6a88-4e2c-9954-97134d560ab3.png)
2. Ran the quickstart:
![image](https://user-images.githubusercontent.com/6767374/142782542-e4fd288a-f1df-472e-b242-1e8acef3370e.png)
3. Ran `Lushify`:
![image](https://user-images.githubusercontent.com/6767374/142782557-66234a65-fd4f-47da-a489-7b5527d7ab8b.png)
4. Uncommented `Normal`:
![image](https://user-images.githubusercontent.com/6767374/142782574-19a90d63-208a-4861-9248-e39da9ee9def.png)
5. Updated the `sea_foam` color:
![image](https://user-images.githubusercontent.com/6767374/142782609-9931001a-c6c0-4432-b34d-1b2bf06f1219.png)

`:messages` just prints blank lines. However, I did notice that if I only remove a single dash from one of the commented lines then I get a Lushify error:

![image](https://user-images.githubusercontent.com/6767374/142782666-dbe0e80c-a9c7-4613-8865-dbedbcacd533.png)



```
λ nvim --version
NVIM v0.5.1
Build type: Release
LuaJIT 2.1.0-beta3
```

I'm on Void Linux

**Comment by rktjmp** [comment]
What does `:set termguicolors?` return?

**Comment by Risto-Stevcev** [comment]
Ah that was it, thanks! It was returning `notermguicolors`
I recently switched to a lua config file and a new terminal emulator, after I fixed my terminal colors everything's working now :)
