### ISSUE TITLE
Lush.ify Could not parse buffer due to Lua error

### ISSUE THREAD

**Issue by thewinger** [rktjmp/lush.nvim#81]
Is there a way to see what in my file is breaking Lushify?

I do Lushify and nothing happens and when I quit the file I have in terminal
```Lush.ify: Could not parse buffer due to Lua error: ...m/site/pack/packer/start/lush.nvim/lua/lush/compiler.lua:9: can't compile, incorrect argument type```

**Comment by rktjmp** [comment]
Is this with a custom theme or just in the tutorial?

Lush tries to give helpful messages but sometimes the lua too broken to start parsing, normally it's a missing `,` or un-closed string.

Can you post your spec file?

**Comment by thewinger** [comment]
Is a custom theme https://github.com/thewinger/eclipse.nvim
It used to work, so maybe is something I have added lately.

**Comment by rktjmp** [comment]
That loads fine for me and gives accurate errors when I break parts. You'll have to investigate your setup.

I am running a sort of old version of nvim from git, but it should be fine on 0.5 up.
```
NVIM v0.7.0-dev+666-ge225397bc-dirty
```

**Comment by thewinger** [comment]
I'll test around. Thank you for your fast answers.
