### ISSUE TITLE
Lush not consistantly using CursorLineNr element

### ISSUE THREAD

**Issue by OddBread** [rktjmp/lush.nvim#95]
Even after defining a CursorLineNr in my lush config file, it does not appear to want to use it for some reason. It shows up as if it was defined correctly, but when i try to go into something with neovim. ..
![g2lg4l](https://user-images.githubusercontent.com/58830765/177023259-5e66c31c-3fb4-4885-b46a-e3f06be4f8f3.png)
the color of the line does not change. 

Weirdly enough, if i try to use my file browser, which is currently fern...
![tbynf1](https://user-images.githubusercontent.com/58830765/177023294-87ac537f-e031-4057-acb2-0f6888b7930b.png)
the highlighting works fine.

Currently, I'm using urxvt with a truecolor patch as my terminal, but I've tried with other terminals such as terminator and had the same results. The colorscheme is set right at the top of my init.lua, right after enabling truecolor. I'm not quite sure if this is an issue with lush, or if I just did something wrong when setting up lush/neovim.

**Comment by rktjmp** [comment]
Not sure, I can't reproduce the errant behaviour here. For what its worth, I set my colorscheme pretty late, almost last in my config, potentially there is a plugin that might be doing some thing funny with the `CursorLineNr` group?

Do you get the issue with a minimal config of just lush and your scheme?

**Comment by OddBread** [comment]
> Not sure, I can't reproduce the errant behaviour here. For what its worth, I set my colorscheme pretty late, almost last in my config, potentially there is a plugin that might be doing some thing funny with the `CursorLineNr` group?
> 
> Do you get the issue with a minimal config of just lush and your scheme?

oh my god, I'm an idiot...
I didnt know you had to use ':set cursorline' to get the cursorline/linenr highlighting to work.
sorry about that, I'm still getting comfortable setting up neovim.

**Comment by rktjmp** [comment]
No worries, Have fun!
